version: "3.8"

services:
  api-gateway:
    image: samiayachi/api-gateway:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    environment:
      - SERVICE1_URL=http://service1:3001
      - SERVICE2_URL=http://service2:3002
    depends_on:
      - service1
      - service2
    networks:
      - microservices-network

  service1:
    image: samiayachi/kamarket-express-server:${BUILD_NUMBER}
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  service2:
    image: samiayachi/oms-express-server:${BUILD_NUMBER}
    ports:
      - "3002:3002"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge