# docker-compose.yml
version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - SERVICE1_URL=http://service1:3001
      - SERVICE2_URL=http://service2:3002
    depends_on:
      - service1
      - service2
    networks:
      - microservices-network

  service1:
    build: ./Kamarket-express-server
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  service2:
    build: ./oms-express-server
    ports:
      - "3002:3002"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
